  <!-- FOOTER -->
  <div class="green-foot">
  <div class="content-area">
  	<div class="footer-equal">
    <h3>About Pl&aacute;tano Solutions</h3>
    <p>Pl&aacute;tano Solutions was never founded since it does not exist. We concentrate on providing our customers with the best imaginary solutions to all your imaginary problems. From unicorns, to leprechauns, there's nothing we cannot handle.</p>
    <p>Be sure to ask us about our special rates for imaginary companies!</p>
    </div>
    <div class="footer-equal">
    <h3>Contact Us</h3>
    <p><strong>P: 787 787 7878</strong></p>
    <p><strong>F: 787 787 8787</strong></p>
    <p><strong>E: sales@platano.com</strong></p>
    <p><strong>#1 Pl&aacute;tano Drive <br /> Mata de Pl&aacute;tano, PR 009Guineito</strong></p>
    </div>
    <div class="footer-equal">
    <h3>Connect with Us</h3>
        <p class="social">
        <img class="social" src="images/64-twitter.png" alt="Find us on Twitter" height="32" width="32" />
        <img class="social" src="images/64-facebook.png" alt="Find us on Facebook" height="32" width="32" />
        <img class="social" src="images/64-linkedin.png" alt="Find us on LinkedIn" height="32" width="32" />
        </p>
    </div>
  
  </div>
  </div>
  <div class="dark">
  <div class="content-area">
      <p class="copy-text">Copyright &copy; 2354 - 2566. Absolutely no rights reserved. If you can read this you don’t need glasses</p>
      </div>
  </div>