  <div id="menu">
      <h3>Welcome, [USERNAME]</h3>
      <!-- BUTTONS -->
      <div class="menu-but"><a href="#">Home</a></div>
      <div class="menu-but"><a href="#">Manage my Account</a></div>
      <div class="menu-but"><a href="#">Change my Password</a></div>
      
      <!-- ADMIN BUTTONS -->
      <div class="menu-but"><a href="#">Create Account</a></div>
      <div class="menu-but"><a href="#">Search for Account</a></div>
      <div class="menu-but"><a href="#">Manage Categories</a></div>
      <div class="menu-but"><a href="#">Reports</a></div>
  </div>